AplicacionWEB/Controllers/ReportePagoController.cs
using AplicacionWEB.Models;
using AplicacionWEB.Models.VerificarSession;
using ModelDomain.Interfaces;
using ModelDomain.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using AplicacionWEB.Models.Util;

namespace AplicacionWEB.Controllers
{
    [SessionExpireAttribute]
    [RoleAuthorize()]

    public class ReportePagoController : Controller
    {
        IPagosEnLinea_Repo PagosEnLinea_Repo;

        public ReportePagoController(IPagosEnLinea_Repo pagosEnLinea_Repo)
        {
            PagosEnLinea_Repo = pagosEnLinea_Repo;
        }

        // GET: ReportePago
        public ActionResult Listado_Pagos(string sortOrder , string currentFilter, string searchString, string currentFechaInicio, string FechaInicio, string currentFechaFin, string FechaFin, string currentFolioPagoInterno, string FolioPagoInterno,int? page)
        {
            IQueryable<PagosEnLineaView> listaPagosEnLinea;
            int pageSize = 10;
            int pageNumber = 0;

            try
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.FechaSortParam= String.IsNullOrEmpty(sortOrder) ? "fecha_asc" : "";


                var dbPagosEnLinea = PagosEnLinea_Repo.Tra_Pago_En_Linea;


                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }


                if (FechaInicio != null)
                {
                    page = 1;
                }
                else
                {
                    FechaInicio = currentFechaInicio;
                }


                if (FechaFin != null)
                {
                    page = 1;
                }
                else
                {
                    FechaFin = currentFechaFin;
                }


                if (FolioPagoInterno != null) {
                    page = 1;
                }else
                {
                    FolioPagoInterno = currentFolioPagoInterno;
                }

                ViewBag.CurrentFechaInicio = FechaInicio;
                ViewBag.CurrentFechaFin = FechaFin;
                ViewBag.CurrentFilter = searchString;
                ViewBag.currentFolioPagoInterno = FolioPagoInterno;


                if (!String.IsNullOrEmpty(searchString)) {

                    dbPagosEnLinea = dbPagosEnLinea.Where(x => x.Tra_Pagos_Solicitudes.Tra_Tramites_Solicitados.RPU.Contains(searchString)
                    || x.Tra_Pagos_Solicitudes.Tra_Tramites_Solicitados.Usuario_Creo.ToLower().Contains(searchString.ToLower())
                    || x.Tra_Pagos_Solicitudes.Codigo_Barras.Contains(searchString)
                    );
                }


                if (!String.IsNullOrEmpty(FolioPagoInterno))
                {
                    int folio = 0;
                    int.TryParse(FolioPagoInterno, out folio);

                    dbPagosEnLinea = dbPagosEnLinea.Where(x => x.Pago_Solicitudes_ID == folio);

                }

                    if (!String.IsNullOrEmpty(FechaInicio))
                {
                    DateTime dateTimeIncio = Cls_Util.ConvertirCadenaFecha(FechaInicio);
                    dbPagosEnLinea = dbPagosEnLinea.Where(x => x.Fecha >= dateTimeIncio);
                }

                if (!String.IsNullOrEmpty(FechaFin)) {
                    DateTime dateTimeFin = Cls_Util.ConvertirCadenaFecha(FechaFin);
                    DateTime dateTimeFinMas = dateTimeFin.AddHours(23).AddMinutes(59).AddSeconds(59);
                    dbPagosEnLinea = dbPagosEnLinea.Where(x => x.Fecha <= dateTimeFinMas);
                }


                    switch (sortOrder) {

                    case "fecha_asc":
                        dbPagosEnLinea = dbPagosEnLinea.OrderBy(x => x.Fecha);
                        break;
                    default:
                        dbPagosEnLinea = dbPagosEnLinea.OrderByDescending(x => x.Fecha);
                        break;
                           
                }

                pageNumber = (page ?? 1);

                listaPagosEnLinea = dbPagosEnLinea.Select(x => new PagosEnLineaView
                {
                    Banco_Emisor = x.Banco_Emisor,
                    Correo_Electronico = x.Correo_Electronico,
                    Fecha_Pago = x.Fecha,
                    Folio_Pago = x.Folio_Pago,
                    Folio_Solicitud = x.Tra_Pagos_Solicitudes.Tramite_Solicitados_ID,
                    Nombre_CuentaHabiente = x.Nombre_CuentaHabiente,
                    Importe = x.Importe,
                    Nombre_Tramite = x.Tra_Pagos_Solicitudes.Tra_Tramites_Solicitados.Tra_Tramites.Nombre_Tramite,
                    No_Diverso = x.No_Diverso,
                    Numero_Aprobacion_Bancaria = x.Numero_Aprobacion_Bancaria,
                    Referencia = x.Referencia,
                    RPU = x.Tra_Pagos_Solicitudes.Tra_Tramites_Solicitados.RPU,
                    Telefono = x.Telefono,
                    Tipo_Pago = x.Tipo_Pago,
                    Tipo_Tarjeta = x.Tipo_Tarjeta,
                    Codigo_Barras = x.Tra_Pagos_Solicitudes.Codigo_Barras,
                    Pago_Solicitudes_ID = x.Pago_Solicitudes_ID,
                    Usuario = x.Tra_Pagos_Solicitudes.Tra_Tramites_Solicitados.Usuario_Creo

                });

            }
            catch (Exception ex) {
                listaPagosEnLinea = Enumerable.Empty<PagosEnLineaView>().AsQueryable();
                pageNumber = 1;
                pageSize = 1;
            }



            return View(listaPagosEnLinea.ToPagedList(pageNumber,pageSize));
        }
    }
}

AplicacionWEB/Views/ReportePago/Listado_Pagos.cshtml
@model PagedList.IPagedList<ModelDomain.ViewModel.PagosEnLineaView>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Listado Pagos";
}

<link type="text/css" href="~/Content/collapse.css" rel="stylesheet" />

@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")


    <script type="text/javascript">

        var objReportePagosEnLinea;
        var Ruta_Reporte = '@Url.Action("Elaborar_Reporte_Pagos_En_Linea", "ExcelExport")';

        $(function () {


            objReportePagosEnLinea = new busquedaPagoEnLinea();
            objReportePagosEnLinea.errors = ko.validation.group(objReportePagosEnLinea);
            ko.applyBindings(objReportePagosEnLinea, $("#buscar_pagos")[0]);

            //Array para dar formato en español
            $.datepicker.regional['es'] =
            {
                closeText: 'Cerrar',
                prevText: 'Previo',
                nextText: 'Próximo',

                monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun',
                'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                monthStatus: 'Ver otro mes', yearStatus: 'Ver otro año',
                dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sáb'],
                dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
                dateFormat: 'dd/mm/yy', firstDay: 0,
                initStatus: 'Selecciona la fecha', isRTL: false
            };

            $(".datefield").datepicker($.datepicker.regional["es"]);

            $("#form_reporte_pagos_linea").submit(function (e) {


                var respuesta = objReportePagosEnLinea.estaValidado();

                if (respuesta == false) {

                    $.toast({
                        heading: 'Reporte de Pagos',
                        text: 'Algunos valores son incorrectos',
                        position: 'top-right',
                        stack: false

                    });

                    e.preventDefault();
                }


            });

            objReportePagosEnLinea.asignarValores();

        });


        function exportarExcel() {

            var respuesta = objReportePagosEnLinea.estaValidado();

            if (respuesta == false) {

                $.toast({
                    heading: 'Reporte de Pagos',
                    text: 'Algunos valores son incorrectos',
                    position: 'top-right',
                    stack: false

                });

                return;
            }

            window.location = Ruta_Reporte + "?searchString=" + objReportePagosEnLinea.buqueda() + "&FechaInicio=" + objReportePagosEnLinea.fechaInicio() + "&FechaFin=" + objReportePagosEnLinea.fechaFin() + "&FolioPagoInterno=" + objReportePagosEnLinea.folioPagoInterno();
        }

        function busquedaPagoEnLinea() {

            var self = this;
            ko.validation.locale('es-ES');
            "use strict";

            self.fechaInicio = ko.observable('').extend({ esFecha: true });
            self.fechaFin = ko.observable('').extend({ esFecha: true });

            self.buqueda = ko.observable('').extend({ caracterPermitido: 'ÁÉÍÓÚáéíóúñÑ_/-()' })
            .extend({ maxLength: 50 });

            self.folioPagoInterno = ko.observable('')
             .extend({ digit: true })
             .extend({ maxLength: 5 });

            self.asignarValores = function () {

                self.fechaInicio('@ViewBag.CurrentFechaInicio');
                self.fechaFin('@ViewBag.CurrentFechaFin');
                self.buqueda('@ViewBag.CurrentFilter');
                self.folioPagoInterno('@ViewBag.currentFolioPagoInterno')
            }


            self.limpiar = function () {

                self.fechaInicio('');
                self.fechaFin('');
                self.buqueda('');
                self.folioPagoInterno('')
            }

            self.estaValidado = function () {
                var respuesta = true;


                if (self.errors().length > 0) {
                    self.errors.showAllMessages();
                    respuesta = false;
                }

                return respuesta;

            }

        }

    </script>


}


    <div class="container">

        <div class="page-header ">
            <h3>Reporte de pagos en l&iacute;nea</h3>
        </div>



        <div id="buscar_pagos">

            <div class="panel panel-default">

                <div class="panel-heading panel-heading-custom clearfix">

                    <div class="panel-title pull-left" style="padding-top: 7.5px;">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#busqueda">
                            Filtros
                        </a>
                    </div>

                    <div class="btn-group pull-right">
                        <button class="btn btn-primary btn-sm" data-bind="click:limpiar"> Borrar Filtros <span class="glyphicon glyphicon-remove-circle"></span></button>
                    </div>

                </div>
                
                <div id="busqueda" class="panel-collapse collapse in">

                    <div class="panel-body">

                        @using (Html.BeginForm("Listado_Pagos", "ReportePago", FormMethod.Get, new { id = "form_reporte_pagos_linea" }))
                        {


                        <div class="form-horizontal">

                            <div class="form-group">
                                <label class="col-md-2">Fecha Inicio</label>
                                <div class="col-md-4">
                                    @Html.TextBox("FechaInicio", ViewBag.CurrentFechaInicio as string, htmlAttributes: new { @class = "form-control datefield", @maxlength = "10", data_bind = "textInput:fechaInicio", autocomplete = "off" })
                                </div>

                                <label class="col-md-2">Fecha Fin</label>
                                <div class="col-md-4">
                                    @Html.TextBox("FechaFin", ViewBag.CurrentFechaFin as string, htmlAttributes: new { @class = "form-control datefield", @maxlength = "10", data_bind = "textInput:fechaFin", autocomplete = "off" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2">B&uacute;queda</label>
                                <div class="col-md-4">
                                    @Html.TextBox("searchString", ViewBag.currentFilter as string, htmlAttributes: new { @class = "form-control", @maxlength = "40", placeholder = "Usuario,RPU,CódigoBarras" , data_bind = "textInput:buqueda", autocomplete = "off" })
                                </div>

                                <label class="col-md-2">Folio Pago Interno</label>
                                <div class="col-md-4">
                                    @Html.TextBox("FolioPagoInterno", ViewBag.currentFolioPagoInterno as string, htmlAttributes: new { @class = "form-control", @maxlength = "10", data_bind = "textInput:folioPagoInterno", autocomplete = "off" })
                                </div>
                            </div>

                        </div>

                            <div class="row">
                                <div class="col-md-12">

                                    <div class="btn-group pull-right">

                                        <button type="submit" class="btn btn-primary btn-sm">
                                            Buscar <i class="glyphicon glyphicon-search"></i>
                                        </button>

                                    </div>
                                    
                                </div>
                            </div>

                        }

                    </div>

                </div>

            </div>

        </div>


        <div class="panel panel-default">

            <div class="panel-heading panel-heading-custom clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;"> Listado </h4>

                <div class="btn-group pull-right">
                    <button class="btn btn-primary btn-sm" onclick="exportarExcel();" > Exportar Excel <span class="glyphicon glyphicon-circle-arrow-down"></span></button>
                </div>

            </div>

            <div class="panel-body">

                <div class="row">

                    <div class="col-md-12">

                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">
                                <tr>
                                    <th>
                                        @Html.ActionLink("Fecha", "Listado_Pagos", new { sortOrder = ViewBag.FechaSortParam, currentFilter = ViewBag.CurrentFilter, currentFechaInicio = ViewBag.CurrentFechaInicio, currentFechaFin = ViewBag.CurrentFechaFin, currentFolioPagoInterno = ViewBag.currentFolioPagoInterno })
                                    </th>
                                    <th>Folio Pago Interno</th>
                                    <th>Folio Solicitud</th>
                                    <th>RPU</th>
                                    <th>Tr&aacute;mite</th>
                                    <th>C&oacute;digo Barras</th>
                                    <th>Correo Electr&oacute;nico</th>
                                    <th>Usuario</th>
                                    <th>Importe</th>
                                </tr>
                                @foreach(var item in Model)
                                {
                                    <tr>
                                        <td> @Html.DisplayFor(m => item.Fecha_Pago)</td>
                                        <td> @item.Pago_Solicitudes_ID </td>
                                        <td> @item.Folio_Solicitud </td>
                                        <td> @item.RPU </td>
                                        <td> @item.Nombre_Tramite </td>
                                        <td> @item.Codigo_Barras </td>
                                        <td> @item.Correo_Electronico </td>
                                        <td> @item.Usuario </td>
                                        <td> @item.Importe </td>
                                    </tr>
                                    
                                }
                            </table>

                        </div>

                    </div>

                </div>


                <div class="row">
                    <div class="col-md-12" style="text-align:right">
                        P&aacute;gina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("Listado_Pagos",
                         new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter , currentFechaInicio = ViewBag.CurrentFechaInicio , currentFechaFin = ViewBag.CurrentFechaFin, currentFolioPagoInterno = ViewBag.currentFolioPagoInterno }))
                    </div>


                </div>

            </div>


        </div>



    </div>