AplicacionWEB/Controllers/AsociarRPUController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using AplicacionWEB.Models;
using AplicacionWEB.Models.Util;
using ModelDomain.Dto;
using ModelDomain.ViewModel;
using ModelDomain.Interfaces;
using AplicacionWEB.Models.VerificarSession;
using AplicacionWEB.Models.Enums;

namespace AplicacionWEB.Controllers
{
    [SessionExpireAttribute]
    [RoleAuthorize(Roles.Usuario_Externo)]
    public class AsociarRPUController : Controller
    {
        IAsociarRPU_Repo AsociarRPU_Repo;

        public AsociarRPUController(IAsociarRPU_Repo asociarRPU_Repo)
        {
            AsociarRPU_Repo = asociarRPU_Repo;

        }


        public ActionResult Agregar_RPU()
        {
            ViewBag.Usuario_ID = Cls_Sesiones.USUARIO_ID;
            return View();
        }

        
        

        // GET: AsociarRPU
        public ActionResult Listar_RPU()
        {
            ViewBag.Usuario_ID = Cls_Sesiones.USUARIO_ID;

            return View();
        }

        [HttpGet]
        public string Obtener_Datos_Cuenta(string RPU) {

            string str_datos = "";
            string str_informacion;
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            Cls_Mensaje_Servidor objMensajeServidor = new Cls_Mensaje_Servidor();
            try
            {
                List<DatosCuentaView> Lista_Datos_Cuenta = AsociarRPU_Repo.Obtener_Datos_Cuenta(RPU);
                str_informacion = serializer.Serialize(Lista_Datos_Cuenta);

                if (Lista_Datos_Cuenta.Count == 0) {
                    objMensajeServidor.Mensaje = "No se encontro información con el rpu escrito";
                    str_datos = serializer.Serialize(objMensajeServidor);
                    return str_datos;
                }

                objMensajeServidor.Mensaje = "bien";
                objMensajeServidor.Dato1 = str_informacion;
              

            }
            catch (Exception ex) {
                objMensajeServidor.Mensaje = ex.Message;
            }

            str_datos = serializer.Serialize(objMensajeServidor);
            return str_datos;
        }

        public string Obtener_RPU_Asociados(int offset, int limit, int Usuarios_ID) {

            Cls_Paginado<RPUAsociadosView> Paginado;
            string str_datos = "{}";
            JavaScriptSerializer serializer = new JavaScriptSerializer();

            try
            {
                Paginado = AsociarRPU_Repo.Obtener_RPU_Asociados(offset, limit, Usuarios_ID);
                str_datos = serializer.Serialize(Paginado);
            }
            catch (Exception ex) {

            }

            return str_datos;
        }

        [HttpPost]
        public string Registar_RPU_Asociado(RPUAsociadosView rPUAsociadosView)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            Cls_Mensaje_Servidor objMensajeServidor = new Cls_Mensaje_Servidor();
            string str_datos = "";

            try
            {

                if(AsociarRPU_Repo.Esta_Repetido_RPU(rPUAsociadosView.RPU,rPUAsociadosView.Usuarios_ID) == "SI")
                {
                    objMensajeServidor.Mensaje = "El RPU ya esta agregado";
                    str_datos = serializer.Serialize(objMensajeServidor);
                    return str_datos;
                }

                rPUAsociadosView.Usuario_Creo = Cls_Sesiones.NOMBRE_COMPLETO;
                AsociarRPU_Repo.Guardar_RPU_Asociados(rPUAsociadosView);

                List<ComboView> Lista_RPU_Asociados = AsociarRPU_Repo.Obtener_RPU_Asociados_Combo(Cls_Sesiones.USUARIO_ID);

                objMensajeServidor.Mensaje = "bien";
                objMensajeServidor.Dato1 = serializer.Serialize(Lista_RPU_Asociados);

            }
            catch (Exception ex) {
                objMensajeServidor.Mensaje = ex.Message;
            }

            str_datos = serializer.Serialize(objMensajeServidor);
            return str_datos;

        }

        [HttpPost]
        public string Eliminar_RPU_Asociado(RPUAsociadosView rPUAsociadosView ) {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            Cls_Mensaje_Servidor objMensajeServidor = new Cls_Mensaje_Servidor();
            string str_datos = "";

            try
            {
                objMensajeServidor.Mensaje = AsociarRPU_Repo.Eliminar_RPU_Asociados(rPUAsociadosView.RPU_Asociados_ID);

            }
            catch (Exception ex) {
                objMensajeServidor.Mensaje = ex.Message;
            }

            str_datos = serializer.Serialize(objMensajeServidor);
            return str_datos;
        }


    }
}

AplicacionWEB/Controllers/ConstanciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using AplicacionWEB.Models;
using AplicacionWEB.Models.Util;
using ModelDomain.Dto;
using ModelDomain.ViewModel;
using ModelDomain.Interfaces;
using AplicacionWEB.Models.VerificarSession;
using ModelDomain.Contexto;
using System.Data.Entity;
using System.Configuration;
using Newtonsoft.Json;
using AplicacionWEB.Models.Enums;


namespace AplicacionWEB.Controllers
{
    [SessionExpireAttribute]
    [RoleAuthorize(Roles.Usuario_Externo)]
    public class ConstanciaController : Controller
    {
        ITramitesProceso_Repo TramitesProceso_Repo;
        ITramites_Documento_Repo Tramites_Documento_Repo;
        IAsociarRPU_Repo AsociarRPU_Repo;
        ITramitesSolicitudes_Repo TramitesSolicitudes_Repo;
        IRoles_Repositorio Roles_Repositorio;
        ITramites_Repo Tramite_Repositorio;
        IMensajesSolicitudes_Repo MensajesSolicitudes_Repo;


        public ConstanciaController(ITramitesProceso_Repo tramitesProceso_Repo,
              IAsociarRPU_Repo asociarRPU_Repo,
              ITramites_Documento_Repo tramites_Documento_Repo,
              ITramitesSolicitudes_Repo tramitesSolicitudes_Repo,
              IRoles_Repositorio roles_Repositorio,
              ITramites_Repo tramites_Repo,
              IMensajesSolicitudes_Repo mensajesSolicitudes_Repo)
        {
            this.TramitesProceso_Repo = tramitesProceso_Repo;
            this.AsociarRPU_Repo = asociarRPU_Repo;
            this.Tramites_Documento_Repo = tramites_Documento_Repo;
            this.TramitesSolicitudes_Repo = tramitesSolicitudes_Repo;
            this.Roles_Repositorio = roles_Repositorio;
            this.Tramite_Repositorio = tramites_Repo;
            this.MensajesSolicitudes_Repo = mensajesSolicitudes_Repo;
        }

        // GET: Constancia
        [HttpGet]
        public ActionResult Crear(int Tramite_ID)
        {
            TramitesSolicitudView solicitudView = new TramitesSolicitudView();
            try
            {
                JavaScriptSerializer serializer = new JavaScriptSerializer();
                List<ComboView> Lista_Documentos = Tramites_Documento_Repo.Obtener_Documentos_Por_Tramite(Tramite_ID);
                TramitesView tramitesView = TramitesProceso_Repo.Obtener_Un_Tramite(Tramite_ID);
                solicitudView.Tramite_ID = Tramite_ID;
                solicitudView.Usuarios_ID = Cls_Sesiones.USUARIO_ID;
                solicitudView.RPU_Requerido = true;
                solicitudView.Estatus = "PENDIENTE";
                solicitudView.Estatus_Revision = "PENDIENTE";
                solicitudView.Seleccionado = true;
                solicitudView.Costo_Tramite = tramitesView.Costo_Tramite;
                solicitudView.Nombre_Tramite = tramitesView.Nombre_Tramite;
                solicitudView.Costo_Tramite = Tramite_Repositorio.Obtener_Costos_Tramite(Tramite_ID);
                List<ComboView> Lista_RPU_Asociados = AsociarRPU_Repo.Obtener_RPU_Asociados_Combo(Cls_Sesiones.USUARIO_ID);
                ViewBag.Lista_RPU_Asociados = serializer.Serialize(Lista_RPU_Asociados);
                ViewBag.Lista_Documentos = serializer.Serialize(Lista_Documentos);

                FormularioConstanciaView formularioConstanciaView = new FormularioConstanciaView();
                ViewBag.Formulario_Constancia = serializer.Serialize(formularioConstanciaView);

            }
            catch (Exception ex) {
               
            }

            return View("FormConstancia",solicitudView);
        }

        [HttpGet]
        public ActionResult Editar(int Tramite_Solicitados_ID,string returnUrl) {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            TramitesSolicitudView solicitudView = new TramitesSolicitudView();
            FormularioConstanciaView formularioConstanciaView;

            try
            {
                TempData["tramite_solicitado_id"] = Tramite_Solicitados_ID;
                solicitudView = TramitesSolicitudes_Repo.Obtener_Una_Solicitud(Tramite_Solicitados_ID);
                solicitudView.RPU_Requerido = true;
                solicitudView.Seleccionado = true;

                if (Cls_Sesiones.ROL.ToLower() == "ejecutivo")
                {
                    solicitudView.Seleccionado = false;
                }

                List<ComboView> Lista_Documentos = Tramites_Documento_Repo.Obtener_Documentos_Por_Tramite(solicitudView.Tramite_ID);
                List<ComboView> Lista_RPU_Asociados = AsociarRPU_Repo.Obtener_RPU_Asociados_Combo(Cls_Sesiones.USUARIO_ID);
                ViewBag.Lista_RPU_Asociados = serializer.Serialize(Lista_RPU_Asociados);
                ViewBag.Lista_Documentos = serializer.Serialize(Lista_Documentos);

                formularioConstanciaView = new FormularioConstanciaView();
                formularioConstanciaView = TramitesProceso_Repo.Obtener_Formulario_Constancia(solicitudView.Tramite_Solicitados_ID);
                ViewBag.Formulario_Constancia = serializer.Serialize(formularioConstanciaView);
                ViewBag.ReturnUrl = returnUrl;
            }
            catch (Exception ex) {
               
                formularioConstanciaView = new FormularioConstanciaView();
            }

            return View("FormConstancia", solicitudView);

        }


        [HttpPost]
        public string Editar(string strSolicitudTramites, string strListaDocumentos, string strFormConstancia) {

            JavaScriptSerializer serializer = new JavaScriptSerializer();
            Cls_Mensaje_Servidor objMensajeServidor = new Cls_Mensaje_Servidor();
            string str_datos = "";
            EFDbContext Contexto = new EFDbContext();
            string rutaPrimeraParte = HttpContext.Server.MapPath("~/Documentos/");
            string urlArchivo = ConfigurationManager.AppSettings["url_documento"];
          

            TramitesSolicitudView tramitesSolicitudView;
            List<Tra_Tramites_Solicitados_DocumentosView> listaDocumentos;
            FormularioConstanciaView formularioConstanciaView;
            MensajesSolicitudesView mensajesSolicitudesView = new MensajesSolicitudesView();

            using (DbContextTransaction transaction = Contexto.Database.BeginTransaction())
            {

                try
                {
                    strSolicitudTramites = strSolicitudTramites.Replace(@"\", "");
                    tramitesSolicitudView = JsonConvert.DeserializeObject<TramitesSolicitudView>(strSolicitudTramites);
                    strListaDocumentos = strListaDocumentos.Replace(@"\", "");
                    listaDocumentos = JsonConvert.DeserializeObject<List<Tra_Tramites_Solicitados_DocumentosView>>(strListaDocumentos);
                    formularioConstanciaView = JsonConvert.DeserializeObject<FormularioConstanciaView>(strFormConstancia);

                    TramitesSolicitudes_Repo.Guardar_Archivos(listaDocumentos, rutaPrimeraParte, urlArchivo);
                    tramitesSolicitudView.Usuario_Creo = Cls_Sesiones.NOMBRE_COMPLETO;
                    TramitesSolicitudes_Repo.Editar_Solicitud_Tramite(Contexto, tramitesSolicitudView, listaDocumentos);

                    TramitesProceso_Repo.Editar_Datos_Constancia(Contexto, formularioConstanciaView);

                    mensajesSolicitudesView.Estatus_Solicitud = tramitesSolicitudView.Estatus_Revision;
                    mensajesSolicitudesView.Nombre_Tramite = TramitesSolicitudes_Repo.Obtener_Nombre_Tramite(Contexto, tramitesSolicitudView.Tramite_Solicitados_ID);
                    mensajesSolicitudesView.Entidad = "USUARIO";
                    mensajesSolicitudesView.Mensaje = "EDICIÓN DE LA SOLICTUD DE TRÁMITE";
                    mensajesSolicitudesView.Tramite_Solicitados_ID = tramitesSolicitudView.Tramite_Solicitados_ID;
                    mensajesSolicitudesView.Usuarios_ID = Cls_Sesiones.USUARIO_ID;
                    mensajesSolicitudesView.Usuario_Creo = Cls_Sesiones.NOMBRE_COMPLETO;
                    mensajesSolicitudesView.Visto = false;

                    MensajesSolicitudes_Repo.Guardar_Mensaje(Contexto, mensajesSolicitudesView);

                    transaction.Commit();
                    objMensajeServidor.Mensaje = "bien";
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    objMensajeServidor.Mensaje = ex.Message;
                }
                finally
                {
                    Contexto.Dispose();
                }
            }

            str_datos = serializer.Serialize(objMensajeServidor);

            return str_datos;
        }


        [HttpPost]
        public string Guardar(string strSolicitudTramites, string strListaDocumentos, string strFormConstancia) {

            JavaScriptSerializer serializer = new JavaScriptSerializer();
            Cls_Mensaje_Servidor objMensajeServidor = new Cls_Mensaje_Servidor();
            string str_datos = "";
            EFDbContext Contexto = new EFDbContext();
            string rutaPrimeraParte = HttpContext.Server.MapPath("~/Documentos/");
            string urlArchivo = ConfigurationManager.AppSettings["url_documento"];
            int Tramite_Solicitados_ID = 0;

            TramitesSolicitudView tramitesSolicitudView;
            List<Tra_Tramites_Solicitados_DocumentosView> listaDocumentos;
            FormularioConstanciaView formularioConstanciaView;

            using (DbContextTransaction transaction = Contexto.Database.BeginTransaction()) {

                try
                {
                    tramitesSolicitudView = JsonConvert.DeserializeObject<TramitesSolicitudView>(strSolicitudTramites);
                    listaDocumentos = JsonConvert.DeserializeObject<List<Tra_Tramites_Solicitados_DocumentosView>>(strListaDocumentos);

AplicacionWEB/Views/Constancia/FormConstancia.cshtml
@model ModelDomain.ViewModel.TramitesSolicitudView
@using AplicacionWEB.Extensiones

@{
    ViewBag.Title = "Constancia No Adeudo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section style{
    <link href="~/Content/steps.css" rel="stylesheet" />
    <link href="~/Content/collapse.css" rel="stylesheet" />
}

@section scripts{


    <script type="text/javascript" src="~/Scripts/SubirArchivos/ajaxupload.3.6.js"></script>
    <script type="text/javascript" src="~/Scripts/Aplicativo/BaseSolicitud/Model/SolicitudTramiteModel.js"></script>
    <script type="text/javascript" src="~/Scripts/Aplicativo/ConstanciaNoAdeudo/Model/ConstanciaModel.js"></script>
    <script type="text/javascript" src="~/Scripts/Aplicativo/BaseSolicitud/UI/BaseSolicitudUI.js"></script>
    <script type="text/javascript" src="~/Scripts/Aplicativo/ConstanciaNoAdeudo/ConstanciaViewModel.js?2"></script>


    <script type="text/javascript">

        // objeto donde esta los datos de la solicitud
        var Model_Solicitud_Tramite = @Html.HtmlConvertToJson(Model);
        var Arreglo_RPU_Asociados = '@Html.Raw(ViewBag.Lista_RPU_Asociados)';
        var Arreglo_Lista_Documentos = '@Html.Raw(ViewBag.Lista_Documentos)';
        var Model_Formulario_Constancia = '@Html.Raw(ViewBag.Formulario_Constancia)';
        var regresarURLOperacion = '@Url.Action("Listar_Mis_Tramites", "MisTramites")';
        var Ruta_Reporte_PDF = '@Url.Action("Visulizar_Archivo_PDF", "VisualizarContenido")';
        var Ruta_Agregar_RPU = '@Url.Action("Agregar_RPU", "AsociarRPU")';
    </script>

}


<div class="container">

    <div class="page-header ">
        <h3> @Model.Nombre_Tramite</h3>
    </div>


    <div class="step step-active">
        <div>
            <div class="circle">1</div>
        </div>
        <div>
            <div class="title">Primer Paso</div>
            <div class="caption">Llenar Solicitud</div>
            <div id="interfaz_constancia">

                <div class="panel panel-default">

                    <div class="panel-heading panel-heading-custom">
                        <div class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#busqueda">
                                Formulario
                            </a>
                        </div>
                    </div>



                    <div id="busqueda" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <form>

                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <label>RPU</label>
                                        <span style="text-align:right"><a href="#" data-bind="click:abrirVentanaAgregarRPU" class="pull-right"> Asociar RPU</a> </span>
                                        <select class="form-control" data-bind="options:ArregloRPU, value:SolicitudTramiteModel.RPU_Selected,optionsText:'name',optionsCaption:'Selecciona',event:{change:eventoRPU }"></select>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label>Nombre del Usuario</label>
                                        <input type="text" class="form-control" data-bind="textInput:ConstanciaModel.Nombre_Usuario,enable: habilitado">
                                    </div>

                                    <div class="form-group col-md-6">
                                        <label>Domicilio</label>
                                        <input type="text" class="form-control" data-bind="textInput:ConstanciaModel.Domicilio,enable: habilitado">
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="form-group col-md-12">
                                        <label>Comentarios</label>
                                        <textarea rows="3" class="form-control" data-bind="textInput:SolicitudTramiteModel.Observaciones"></textarea>
                                    </div>

                                </div>

                            </form>

                        </div>
                    </div>

                    

                </div>

            </div>
        </div>

    </div>


    <div class="step">
        <div>
            <div class="circle">2</div>
        </div>
        <div>
            <div class="title">Segundo Paso</div>
            <div class="caption">Subir Documentos</div>

            @if (Model.Tramite_Solicitados_ID > 0)
            {

                <div class="panel panel-primary">
                    <div class="panel-body">
                        <div class="form-group">
                            <label class="col-md-1 control-label">Folio</label>
                            <div class="col-md-3">
                                <input class="form-control" value="@Model.Tramite_Solicitados_ID" disabled="disabled" />
                            </div>
                            <label class="col-md-1 control-label">RPU</label>
                            <div class="col-md-3">
                                <input class="form-control" value="@Model.RPU" disabled="disabled" />
                            </div>
                            <label class="col-md-1 control-label">Usuario</label>
                            <div class="col-md-3">
                                <input class="form-control" value="@Model.Usuario" disabled="disabled" />
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div id="interfaz_documentos">
                @{Html.RenderAction("CrearVistaDocumentoTitulo", "BaseSolicitudTramite", new { Tramite_ID = Model.Tramite_ID, returnUrl = ViewBag.ReturnUrl });}
            </div>


        </div>

    </div>






</div>


<div id="Ventana_Espera" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Procesando</h4>
            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped active" role="progressbar"
                         aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">

                    </div>
                </div>
            </div>

        </div>

    </div>
</div>